#!/usr/bin/python

import collections
import subprocess
import sys
from mx_btrfs.btrfs_usage import BtrfsUsage, BtrfsUsageException


def btrfs_mounts():
    proc = subprocess.Popen(('grep', 'btrfs', '/proc/mounts'),
                            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                            env={"PATH": "/bin:/sbin"})
    stdout, stderr = proc.communicate()
    if proc.returncode != 0:
        print('grep btrfs /proc/mounts failed: %s, stderr: %s' %
              (stdout, stderr))
        sys.exit(-1)

    return [line.split()[1] for line in stdout.splitlines()]


def btrfs_allocated_used(btrfs_data):
    allocated = collections.OrderedDict()
    used = collections.OrderedDict()
    for alloc_type in ['Data', 'System', 'Metadata']:
        for profile in btrfs_data[alloc_type].keys():
            allocated[alloc_type.lower()] = allocated.get(alloc_type, 0) + \
                to_profile_bytes(btrfs_data[alloc_type][profile]['allocated'], profile)
            used[alloc_type.lower()] = used.get(alloc_type, 0) + \
                to_profile_bytes(btrfs_data[alloc_type][profile]['used'], profile)
    allocated['globalreserve'] = btrfs_data['Overall']['Global reserve']
    used['globalreserve'] = btrfs_data['Overall']['Global reserve used']

    return (allocated, used)


def to_profile_bytes(size, profile):
    p = {
        'single': 1,
        'RAID0': 1,
        'RAID1': 2,
        'DUP': 2,
        'RAID10': 2,
    }
    return int(size) * p[profile]


def colours():
    colours = collections.deque([
        '33FF33', '00CC00',  # green
        'FFFF33', 'CCCC00',  # yellow
        '3399FF', '0000CC',  # blue
        'FF3333', 'CC0000',  # red
        'FF33FF', 'CC00CC',  # purple
    ])
    while True:
        yield colours[0]
        colours.rotate(-1)


def draw_type():
    yield 'AREA'
    while True:
        yield 'STACK'


def munin_config(fsinfo):
    for fsid in fsinfo:
        fs = fsinfo[fsid]
        print("multigraph btrfs_usage_%s" % fs['fsid'].replace('-', '_'))
        print("graph_args --base 1024 -l 0")
        print("graph_vlabel bytes")
        print("graph_title btrfs space usage for %s" % fs['mountpoint'])
        print("graph_category disk")
        print("graph_info This graph shows how btrfs uses available space")
        draw = draw_type()
        colour = colours()
        for alloc_type in fs['allocated']:
            print("%s_used.label Used %s" % (alloc_type, alloc_type))
            print("%s_used.draw %s" % (alloc_type, next(draw)))
            print("%s_used.info Used %s" % (alloc_type, alloc_type))
            print("%s_used.colour %s" % (alloc_type, next(colour)))
            print("%s_unused.label Unused %s" % (alloc_type, alloc_type))
            print("%s_unused.draw %s" % (alloc_type, next(draw)))
            print("%s_unused.info Unused %s" % (alloc_type, alloc_type))
            print("%s_unused.colour %s" % (alloc_type, next(colour)))
        print("unallocated.label Unallocated")
        print("unallocated.draw STACK")
        print("unallocated.info Not allocated raw space")
        print("unallocated.colour FFFFFF")
        print("wasted_soft.label Reclaimable non-alloc")
        print("wasted_soft.draw STACK")
        print("wasted_soft.info Reclaimable not allocatable")
        print("wasted_soft.colour BBBBBB")
        print("wasted_hard.label Non-allocatable")
        print("wasted_hard.draw STACK")
        print("wasted_hard.info Non-allocatable")
        print("wasted_hard.colour 888888")
        print("total.label Total")
        print("total.draw LINE2")
        print("total.info Total raw space")
        print("total.colour 000000")
        print("")


def munin_values(fsinfo):
    for fsid in fsinfo:
        fs = fsinfo[fsid]
        print("multigraph btrfs_usage_%s" % fs['fsid'].replace('-', '_'))
        total_allocated = 0
        for alloc_type in fs['allocated']:
            used = fs['used'][alloc_type]
            allocated = fs['allocated'][alloc_type]
            total_allocated = total_allocated + allocated
            unused = allocated - used
            print("%s_used.value %s" % (alloc_type, used))
            print("%s_unused.value %s" % (alloc_type, unused))
        total = fs['total']
        unallocated = total - total_allocated - fs['wasted_hard'] - fs['wasted_soft']
        print("unallocated.value %s" % unallocated)
        print("wasted_soft.value %s" % fs['wasted_soft'])
        print("wasted_hard.value %s" % fs['wasted_hard'])
        print("total.value %s" % total)
        print("")


def main():
    fsinfo = collections.OrderedDict()

    for mountpoint in btrfs_mounts():
        try:
            usage = BtrfsUsage(mountpoint)
        except BtrfsUsageException as bue:
            print bue.msg
            sys.exit(-1)
        total = usage.get_total()
        fsid = usage.get_fsid()
        allocated, used = btrfs_allocated_used(usage.data)
        wasted_hard, wasted_soft = usage.get_wasted()

        if fsid not in fsinfo:
            fsinfo[fsid] = {
                'fsid': fsid,
                'total': total,
                'allocated': allocated,
                'used': used,
                'wasted_hard': wasted_hard,
                'wasted_soft': wasted_soft,
                'mountpoint': mountpoint,
            }

    if len(sys.argv) > 1 and sys.argv[1] == "config":
        munin_config(fsinfo)
    else:
        munin_values(fsinfo)

if __name__ == "__main__":
    main()
