#!/usr/bin/python
import sys
import m2ee

m2ee.logger.setLevel(51)

try:
    command = sys.argv[1]
except IndexError:
    command = 'values'

if command == 'autoconf':
    print("no")
else:
    m2ee_instance = m2ee.M2EE()
    m2ee.munin.print_all(
        m2ee_instance.client,
        m2ee_instance.config,
        m2ee_instance.config.get_munin_options(),
        "",
        print_config=(command == 'config')
    )
