#!/usr/bin/python
#
# This plugin show the iSCSI OPS
#
# Usage: symlink this plugin like netapp_iscsiops_hostname
#
# The clean function was used from the Perl version
#
# Install:
# - libsnmp-python
# - python-pysnmp2
# - python-pysnmp-common

import netsnmp
import sys
import os
from os.path import basename

host = basename(sys.argv[0]).replace('netapp_iscsiops_','')

if host == '':
    sys.stderr.write("symlink this plugin like netapp_iscsiops_hostname\n")
    exit(1)

community = os.getenv('community')

def clean(hoog, laag):
    tmp_pow2tot32 = 1 << 32
    if hoog < 0:
        hoog = tmp_pow2tot32 + hoog
    if laag < 0:
        laag = tmp_pow2tot32 + laag
        hoog = hoog + 1

    return hoog * tmp_pow2tot32 + laag

argc = len(sys.argv)
if argc > 1 and sys.argv[1] == 'config':
    print "host_name %s" % host
    print "graph_title iSCSI Operations"
    print "graph_order iscsiops"
    print "graph_vlabel iSCSI OPS per second"
    print "graph_args --base 1000 --lower-limit 0"
    print "graph_info This graph shows how many iSCSI Operations."
    print "graph_category disk"
    print "iscsiops.label iSCSI Ops"
    print "iscsiops.type COUNTER"
    print "iscsiops.info iSCSI Operations"
    exit(0)
else:
    iscsi_ops_high  = netsnmp.Varbind(".1.3.6.1.4.1.789.1.17.11")
    iscsi_ops_low   = netsnmp.Varbind(".1.3.6.1.4.1.789.1.17.12")

    res_iscsi_ops_high = netsnmp.snmpwalk(iscsi_ops_high, Version = 1, DestHost = host, Community = community)
    res_iscsi_ops_low = netsnmp.snmpwalk(iscsi_ops_low, Version = 1, DestHost = host, Community = community)

    print "iscsiops.value %d" % clean(int(res_iscsi_ops_high[0]), int(res_iscsi_ops_low[0]))
    

# vim:ft=python:sw=4:ts=4:expandtab
