#!/usr/bin/python
#
# This plugin show the cache age of a NetApp controller like sysstat -x
#
# Usage: symlink this plugin like netapp_cacheage_hostname
#
# Install:
# - libsnmp-python
# - python-pysnmp2
# - python-pysnmp-common

import netsnmp
import sys
import os
from os.path import basename

host = basename(sys.argv[0]).replace('netapp_cacheage_','')

if host == '':
    sys.stderr.write("symlink this plugin like netapp_cacheage_hostname\n")
    exit(1)

community = os.getenv('community')

argc = len(sys.argv)
if argc > 1 and sys.argv[1] == 'config':
    print "host_name %s" % host;
    print "graph_title Cache Age";
    print "graph_order cacheage";
    print "graph_args --base 1000 --lower-limit 0";
    print "graph_info This graph shows how long till cache purges.";
    print "graph_category system";
    print "cacheage.label Cache Age";
    print "cacheage.info Cache Age in Seconds";
    exit(0)
else:
    oid = netsnmp.Varbind(".1.3.6.1.4.1.789.1.2.2.23")
    result = netsnmp.snmpwalk(oid, Version = 1, DestHost = host, Community = community)

    print "cacheage.value %s" % result[0]

# vim:ft=python:sw=4:ts=4:expandtab
