#!/usr/bin/python
#
# This plugin show the cpu usage of a NetApp controller like sysstat -x
#
# Usage: symlink this plugin like netapp_cpu_hostname
#
# Install:
# - libsnmp-python
# - python-pysnmp2
# - python-pysnmp-common

import netsnmp
import sys
import os
from os.path import basename

host = basename(sys.argv[0]).replace('netapp_cpu_','')

if host == '':
    sys.stderr.write("symlink this plugin like netapp_cpu_hostname\n")
    exit(1)

community = os.getenv('community')

argc = len(sys.argv)
if argc > 1 and sys.argv[1] == 'config':
    print "host_name %s" % host
    print "graph_title CPU usage"
    print "graph_order busy idle"
    print "graph_args  --base 1000 -r --lower-limit 0 --upper-limit 100"
    print "graph_vlabel %"
    print "graph_scale no"
    print "graph_info This graph shows how CPU time is spent."
    print "graph_category system"
    print "graph_period second"
    print "busy.label Busy"
    print "busy.draw AREA"
    print "busy.type DERIVE"
    print "busy.info CPU time"
    print "busy.min 0"
    print "idle.label Idle"
    print "idle.draw STACK"
    print "idle.type DERIVE"
    print "idle.info Idle time"
    print "idle.min 0"
    exit(0)
else:
    cpu_busytime = netsnmp.Varbind(".1.3.6.1.4.1.789.1.2.1.2")
    result = netsnmp.snmpwalk(cpu_busytime, Version = 1, DestHost = host, Community = community)

    cpu_idletime = netsnmp.Varbind(".1.3.6.1.4.1.789.1.2.1.4")
    result2 = netsnmp.snmpwalk(cpu_idletime, Version = 1, DestHost = host, Community = community)

    print "busy.value %s" % result[0]
    print "idle.value %s" % result2[0]

# vim:ft=python:sw=4:ts=4:expandtab
