#!/usr/bin/python

from __future__ import print_function
import requests
import sys


def munin_config():
    print("graph_args --base 1000 -l 0")
    print("graph_vlabel hits")
    print("graph_title TLS Keystore lookups")
    print("graph_category nginx")
    print("graph_info This graph shows the number of TLS Keystore Hits/Misses "
          "and (Negative) Cached Certificates Hits")
    print("cache_hit.label Cache Hit")
    print("cache_hit.draw LINE1")
    print("cache_hit.info Cache Hit")
    print("cache_hit.type DERIVE")
    print("cache_hit.min 0")
    print("ldap_hit.label Keystore Hit")
    print("ldap_hit.draw LINE1")
    print("ldap_hit.info Keystore Hit")
    print("ldap_hit.type DERIVE")
    print("ldap_hit.min 0")
    print("ldap_miss.label Keystore Miss")
    print("ldap_miss.draw LINE1")
    print("ldap_miss.info Keystore Miss")
    print("ldap_miss.type DERIVE")
    print("ldap_miss.min 0")
    print("neg_cache_hit.label Negative Cache Hit")
    print("neg_cache_hit.draw LINE1")
    print("neg_cache_hit.info Negative Cache Hit")
    print("neg_cache_hit.type DERIVE")
    print("neg_cache_hit.min 0")
    print("not_found.label Not Found")
    print("not_found.draw LINE1")
    print("not_found.info Not Found")
    print("not_found.type DERIVE")
    print("not_found.min 0")


def munin_values():
    stats = requests.get('http://localhost:83/keystore/stats').json()
    for key in ['cache_hit', 'ldap_hit', 'ldap_miss', 'neg_cache_hit', 'not_found']:
        print("{0}.value {1}".format(key, stats['crt'][key]))


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        munin_config()
    else:
        munin_values()


if __name__ == "__main__":
    main()
